#!/bin/bash
export PATH="/home/imaarm/.foundry/bin:$PATH"
RPC="https://api.infra.testnet.somnia.network"
FACTORY="0x3E106bA72C3AdB511076Cf849c4A70bb132Be395"
CLONE="0xde6708b735c37a415c35f690ad3532aaea3999c8"

echo "=== Factory Info ==="
echo "implementation():"
cast call --rpc-url "$RPC" "$FACTORY" "implementation()"
echo "defaultFeeBps():"
cast call --rpc-url "$RPC" "$FACTORY" "defaultFeeBps()"
echo "minStake():"
cast call --rpc-url "$RPC" "$FACTORY" "minStake()"
echo "maxStake():"
cast call --rpc-url "$RPC" "$FACTORY" "maxStake()"
echo "feeRecipient():"
cast call --rpc-url "$RPC" "$FACTORY" "feeRecipient()"

echo -e "\n=== Clone Info ==="
echo "state():"
cast call --rpc-url "$RPC" "$CLONE" "state()"
echo "factory():"
cast call --rpc-url "$RPC" "$CLONE" "factory()"
echo "owner():"
cast call --rpc-url "$RPC" "$CLONE" "owner()"
echo "playerA():"
cast call --rpc-url "$RPC" "$CLONE" "playerA()"
echo "playerB():"
cast call --rpc-url "$RPC" "$CLONE" "playerB()"
echo "stakeAmount():"
cast call --rpc-url "$RPC" "$CLONE" "stakeAmount()"
echo "joinDeadline():"
cast call --rpc-url "$RPC" "$CLONE" "joinDeadline()"
echo "address(this).balance:"
cast balance --rpc-url "$RPC" "$CLONE"
echo "deposits(B):"
cast call --rpc-url "$RPC" "$CLONE" "deposits(address)" "0x0022EC010030158cC27B283BA640706eDBa6080f"
echo "deposits(A):"
cast call --rpc-url "$RPC" "$CLONE" "deposits(address)" "0xF241F1A68878996aB1484f27099395c46796bC90"
echo "code:"
cast code --rpc-url "$RPC" "$CLONE"
echo "code length:"
cast code --rpc-url "$RPC" "$CLONE" | wc -c

echo -e "\n=== Try join call (dry) ==="
cast call --rpc-url "$RPC" --private-key "0x76d73b841d6b086cf98dda0f97588ec9f463472b6f016eae73f51b966be7aed7" "$CLONE" "join()"
